
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { getServerSession } from "next-auth";
import { Providers } from "../components/provider";
import { ToggleProvider } from "../components/SearchToggle";
import Sidebar from "../components/Sidebar";
import { authOptions } from '../lib/authOptions';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession(authOptions);
    return (

        <div className="overflow-y-auto flexc z-10 h-screen gap-5 py-2">
            <div className="hidden md:flex fixed top-0 bottom-0 h-full w-[11%] lg:w-1/6 border-[1px] ">
                <Sidebar token={session?.user?.token} />
            </div>
            {children}
        </div>


    );
}
