
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { Providers } from "./components/provider";
import { ToggleProvider } from "./components/SearchToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full `}>
        <Providers>
          <ToggleProvider>{children}</ToggleProvider>
        </Providers>
      </body>
    </html>
  );
}
